### ISSUE TITLE
FileDrop has been renamed FileDragAndDrop

### ISSUE THREAD

**Issue by schulzj01** [chrismbarr/FileDrop#1]
Love the plugin!  

However I had a hard time setting it up initially.  It seems as though the function has been (perhaps accidentally) renamed "FileDragAndDrop" and the documentation still has it listed as "FileDrop"

I  have to call the plugin like this now:
$('html').fileDragAndDrop(
instead of 
$('html').fileDrop

**Comment by ChrisMBarr** [comment]
Wow... I apparently made a really bad commit a while ago and never noticed.  that commit changed the namespace and it also removed several options/features that the docs say that this plugin does.  Thanks for bringing this to my attention!

This should now be fixed with my latest commit: https://github.com/chrismbarr/FileDrop/commit/f70b65c8e5cb6eb939c7d9e791911552080fc7c5

Please download this again and let me know if it's working as expected.

**Comment by schulzj01** [comment]
That is some pretty awesome service!  Thanks Chris!  Once again love the plugin.  Simple and easy to use for my app.
